removing some debug

diff --git a/ci/tasks/validate-via-pitometer b/ci/tasks/validate-via-pitometer
--- a/ci/tasks/validate-via-pitometer
+++ b/ci/tasks/validate-via-pitometer
@@ -1,6 +1,6 @@
 #!/bin/bash
 export
-set -ex
+set -e
 
 echo "configuring Pitometer CLI with $DYNATRACE_APITOKEN and $DYNATRACE_BASEURL"
 
@@ -16,19 +16,18 @@ CURRENT_TIME=$(printf "%(%s)T")
 #setting to validate over last 5 minutes
 START_TIME=$(printf "$(( $(printf "%(%s)T") - 60 * 60 ))")
 
-echo $PWD
-ls -la ./$APP_REPO
-ls -la ./$APP_REPO/$perfspec
+# echo $PWD
+# ls -la ./$APP_REPO
+# ls -la ./$APP_REPO/$perfspec
 
-npm start --prefix /usr/src/app $START_TIME $CURRENT_TIME $PWD/$APP_REPO/$perfspec 
-#| tail -n +5 > pitometer_output.json
-# jq '.' pitometer_output.json
-# result="$(jq -r '.result' pitometer_output.json)"
-# if [ "$result" = "fail" ]; then
-#   echo "This build has failed based on pitometer evaluation"
-#   exit 1
-# else
-#   echo "This build has passed pitometer evaluation"
-#   exit 0
-# fi
+npm start --prefix /usr/src/app $START_TIME $CURRENT_TIME $PWD/$APP_REPO/$perfspec | tail -n +5 > pitometer_output.json
+jq '.' pitometer_output.json
+result="$(jq -r '.result' pitometer_output.json)"
+if [ "$result" = "fail" ]; then
+  echo "This build has failed based on pitometer evaluation"
+  exit 1
+else
+  echo "This build has passed pitometer evaluation"
+  exit 0
+fi
 
